/**
 * Shared responsive-image helpers.
 *
 * Every image under public/optimized/ ships a `<name>.webp` plus a
 * `<name>-800w.webp` sibling generated by scripts/gen-srcset.mjs. These
 * helpers build the srcset/candidate strings so that contract lives in
 * one place.
 */

/** "/optimized/band/karpa.webp" → "/optimized/band/karpa-800w.webp" */
export const widen800 = (src: string): string => src.replace(/\.webp$/, '-800w.webp');

/** srcset with the 800w sibling + the (≤1600px) original. */
export const srcset800 = (src: string): string => `${widen800(src)} 800w, ${src} 1600w`;
