/**
 * The 5 band members, in display order.
 * Photos live at public/optimized/band/<slug>.webp (+ -800w.webp srcset sibling),
 * generated by scripts/gen-srcset.mjs from source-assets/band/.
 */
export interface BandMember {
  name: string;
  instrument: string;
  photo: string;
  alt: string;
}

export const bandMembers: BandMember[] = [
  {
    name: 'Alexander Karpa',
    instrument: 'Vocals',
    photo: '/optimized/band/karpa.webp',
    alt: 'Alexander Karpa, vocalist for Budmo',
  },
  {
    name: 'Luke Udod',
    instrument: 'Accordion',
    photo: '/optimized/band/luke.webp',
    alt: 'Luke Udod, accordionist for Budmo',
  },
  {
    name: 'Simon Reimer',
    instrument: 'Violin',
    photo: '/optimized/band/simon.webp',
    alt: 'Simon Reimer, violinist for Budmo',
  },
  {
    name: 'Marco Freynet',
    instrument: 'Bass',
    photo: '/optimized/band/marco.webp',
    alt: 'Marco Freynet, bassist for Budmo',
  },
  {
    name: 'Andrew Mandziuk',
    instrument: 'Drums',
    photo: '/optimized/band/andrew.webp',
    alt: 'Andrew Mandziuk, drummer for Budmo',
  },
];
